### PR TITLE
Show dialog when save fails to mount 

### PR DESCRIPTION
**Pull request by illusion0001**

### CODE REVIEW

**Comment by bucanero** [comment]
With the added version check, is there any situation where a save fails to mount and the user doesn't get a notification?

**Comment by illusion0001** [comment]
When built using newest oosdk commit it failed to mount.
image

**Comment by bucanero** [comment]
Can you test the same save with the last official release? Just to confirm if it fails with the last 1.4.0 version or not. If not, then the newer SDK introduced issues

**Comment by illusion0001** [comment]
1.4.0 release worked. SDK from April 2022 worked but not newest commit.

**Comment by bucanero** [comment]
> 1.4.0 release worked. SDK from April 2022 worked but not newest commit.

then there's an issue with the new sdk version. Either a data type or structure has changed and is not matching the correct size/format , or some other change from the sdk has an issue.

I'd say that actually this PR should either become a fix for the new SDK issue or goes back to the older sdk that keeps the save-mounting working.

**Comment by illusion0001** [comment]
Yeah. I will look into the changes in the SDK. It will be better to fix the source of the issue

**Comment by bucanero** [comment]
Related to this, probably is better to go back to the old OO-SDK on github actions so any "nightly build" works properly. (until SDK bug gets solved)

**Comment by illusion0001** [comment]
I forgot about this, just got my development environment setup, will check it sometime

**Comment by bucanero** [comment]
Reverted CI script back to older OO-SDK to avoid broken builds.

**Pull request closed without merging**
