### PR TITLE
WIP 11.00 Support

### PR DESCRIPTION
**Pull request by LightningMods**
this PR is co-authored with @SocraticBliss

### CODE REVIEW

**Comment by faroukbmiled** [comment]
great work <3

**Review by bucanero — APPROVED** [review]

**Comment by bucanero** [comment]
> great work <3

if you're on FW 11, please download this [development build](https://github.com/bucanero/apollo-ps4/actions/runs/9166874195/artifacts/1521088770) , and report your results.

**Comment by faroukbmiled** [comment]
> > great work <3
> 
> if you're on FW 11, please download this [development build](https://github.com/bucanero/apollo-ps4/actions/runs/9166874195/artifacts/1521088770) , and report your results.

Works as expected ,haven't found any issues so far (tested all save features)!

**Comment by SLAzurin** [comment]
ive tested the save backup from hdd to usb feature. Works as expected

**Comment by ekurt1** [comment]
I can confirm as well, the current development build works as expected on 11.00, both encrypted backup transfer to and from USB and for save decryption with cheats.

**Pull request merged**
