### PR TITLE
more quick codes added

### PR DESCRIPTION
**Pull request by OfficialAhmed**
Added some .savepatch files and added more quick codes for some games

### CODE REVIEW

**Comment by bucanero** [comment]
Any issues to close it? Some problems?

**Comment by OfficialAhmed** [comment]
many files conflicting

**Comment by bucanero** [comment]
> many files conflicting

alright, just let me know when ready and I'll review and merge 👍 
thanks for the help!

**Comment by bucanero** [comment]
> Fixed conflicts but build package/build_pkg failed in checking.. review it if it doesn’t work I’ll try another pull request

oh the building issue is on my side, I made some code changes that broke the build. (nothing to do with the patches)

**Pull request merged**
